version: "3"

services:
  server1:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  server2:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  server3:
    build: .
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
